version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: dbreadnspeak
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env  # .env 파일을 설정하여 환경 변수를 로드
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
