import type { Metadata } from 'next'

import './globals.css'
import NavBar from '@/components/NavBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="min-w-[750px] md:w-[80%] lg:w-[70%] mx-auto">
          {children}
        </div>
      </body>
    </html>
  )
}
